name: Generate JSON

on: 
  push:
    branches:
      - main
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '45 3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Build contributions file for PDE with default params
        run: |
          cd scripts
          python build_contribs.py
          cd ..
      - name: Build JSON files for website with default params
        run: |
          cd scripts
          python build_json.py
          cd ..
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - name: Push changes back to repo
        if: steps.changes.outputs.changed == 1
        run: |
          git config --global user.name 'P5 Robot'
          git config --global user.email 'p5-bot@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "chore(ci): update contributions [skip ci]"
          git push
      - name: Deploy changes to web
        if: steps.changes.outputs.changed == 1
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} > ~/.ssh/known_hosts
          touch ~/.ssh/id_ed25519
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 400 /home/runner/.ssh/id_ed25519
          sftp ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/var/www/download/contribs <<< $'put ./pde/*'
